language: python
dist: xenial
addons:
  apt:
    packages:
    - snapcraft
python:
- '3.6'
- '3.7'
- '3.8'
- 'pypy3.6'
env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
before_install: ./.travis.sh
install: pip install -r requirements.txt .
before_script:
- git config --global user.name "travis-test"
- git config --global user.email "travis@test.com"
script:
- nosetests --logging-level=WARN
- nosetests gitless/tests/test_e2e.py --logging-level=WARN
branches:
  only:
  - master
  - develop
jobs:
  include:
  - stage: Pack snap
    env: EMPTY
    before_install: skip
    install: skip
    script: snapcraft
    deploy:
      on:
        branch: master
      provider: snap
      snap: "*.snap"
      channel: edge
      skip_cleanup: true
